In [16]:
from sklearn.feature_extraction import DictVectorizer  
data = [
    {'city': '北京','temperature':100},
    {'city': '上海','temperature':60},
    {'city': '深圳','temperature':30},
]

In [18]:
dic = DictVectorizer(sparse=False)
# 数据转换
dat = dic.fit_transform(data)
# 数据分类名称
print(dic.get_feature_names())

print(dat)

# 数据回转，把数据转换为最先的未处理格式
#print(dic.inverse_transform(dat))


['city=上海', 'city=北京', 'city=深圳', 'temperature']
[[  0.   1.   0. 100.]
 [  1.   0.   0.  60.]
 [  0.   0.   1.  30.]]


In [20]:
dic = DictVectorizer(sparse=True)
# 数据转换
dat = dic.fit_transform(data)
# 数据分类名称
print(dic.get_feature_names())

print(dat)

['city=上海', 'city=北京', 'city=深圳', 'temperature']
  (0, 1)	1.0
  (0, 3)	100.0
  (1, 0)	1.0
  (1, 3)	60.0
  (2, 2)	1.0
  (2, 3)	30.0


In [30]:
from sklearn.feature_extraction import DictVectorizer
 
# 设置sparse=False获得numpy ndarray形式的结果
v = DictVectorizer(sparse=False)
D = [{"foo": 1, "bar": 2}, {"foo": 3, "baz": 1}]
print ('{:*^60}'.format('原数据:'))
print(D)
# 对字典列表D进行转换，转换成特征矩阵
X = v.fit_transform(D)
# 特征矩阵的行代表数据，列代表特征，0表示该数据没有该特征
print ('{:*^60}'.format('特征矩阵:'))
print(X)
# 获取特征列名
print ('{:*^60}'.format('特征名称:'))
print(v.get_feature_names())

# inverse_transform可以将特征矩阵还原成原始数据
print ('{:*^60}'.format('还原成原始数据:'))
print(v.inverse_transform(X) == D)

# 直接进行转换，不先进行拟合的话，无法识别新的特征
print ('{:*^60}'.format('直接转换:'))
print(v.transform([{"foo": 4, "unseen_feature": 3}]))

****************************原数据:****************************
[{'foo': 1, 'bar': 2}, {'foo': 3, 'baz': 1}]
***************************特征矩阵:****************************
[[2. 0. 1.]
 [0. 1. 3.]]
***************************特征名称:****************************
['bar', 'baz', 'foo']
**************************还原成原始数据:**************************
True
***************************直接转换:****************************
[[0. 0. 4.]]


In [31]:
from sklearn.feature_extraction import DictVectorizer
 
# 设置sparse=False获得numpy ndarray形式的结果
v = DictVectorizer(sparse=True)
D = [{"foo": 1, "bar": 2}, {"foo": 3, "baz": 1}]
print ('{:*^60}'.format('原数据:'))
print(D)
# 对字典列表D进行转换，转换成特征矩阵
X = v.fit_transform(D)
# 特征矩阵的行代表数据，列代表特征，0表示该数据没有该特征
print ('{:*^60}'.format('特征矩阵:'))
print(X)
# 获取特征列名
print ('{:*^60}'.format('特征名称:'))
print(v.get_feature_names())

# inverse_transform可以将特征矩阵还原成原始数据
print ('{:*^60}'.format('还原成原始数据:'))
print(v.inverse_transform(X) == D)

# 直接进行转换，不先进行拟合的话，无法识别新的特征
print ('{:*^60}'.format('直接转换:'))
print(v.transform([{"foo": 4, "unseen_feature": 3}]))

****************************原数据:****************************
[{'foo': 1, 'bar': 2}, {'foo': 3, 'baz': 1}]
***************************特征矩阵:****************************
  (0, 0)	2.0
  (0, 2)	1.0
  (1, 1)	1.0
  (1, 2)	3.0
***************************特征名称:****************************
['bar', 'baz', 'foo']
**************************还原成原始数据:**************************
True
***************************直接转换:****************************
  (0, 2)	4.0
