In [20]:
from sklearn import preprocessing
enc = preprocessing.OneHotEncoder()
data = [[0, 0, 3], [1, 1, 0], [0, 2, 1], [1, 0, 2]]
print ('{:*^60}'.format('原数据:'))
print(data)
enc.fit(data)    # fit来学习编码
print ('{:*^60}'.format('编码原数据:'))
print(enc.transform(data).toarray())    # 进行编码
print ('{:*^60}'.format('编码数据[0, 1, 3]:'))
print(enc.transform([[0, 1, 3]]).toarray())    # 进行编码


****************************原数据:****************************
[[0, 0, 3], [1, 1, 0], [0, 2, 1], [1, 0, 2]]
***************************编码原数据:***************************
[[1. 0. 1. 0. 0. 0. 0. 0. 1.]
 [0. 1. 0. 1. 0. 1. 0. 0. 0.]
 [1. 0. 0. 0. 1. 0. 1. 0. 0.]
 [0. 1. 1. 0. 0. 0. 0. 1. 0.]]
***********************编码数据[0, 1, 3]:***********************
[[1. 0. 0. 1. 0. 0. 0. 0. 1.]]


In [21]:
# coding:utf-8
from sklearn import preprocessing
 
le = preprocessing.LabelEncoder()
le.fit(["Japan", "china", "Japan", "Korea","china"])
print('标签个数:%s' % le.classes_)
print('标签值标准化:%s' % le.transform(["Japan", "china", "Japan", "Korea","china"]))



标签个数:['Japan' 'Korea' 'china']
标签值标准化:[0 2 0 1 2]


In [22]:

from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
le.fit([1,5,67,100])
le.transform([1,1,100,67,5])

array([0, 0, 3, 2, 1], dtype=int64)

In [1]:
#导入工具包
import pandas as pd
import numpy as np
from sklearn.preprocessing import OneHotEncoder,LabelEncoder
from sklearn.feature_extraction import DictVectorizer

#创建示例数据：离散无序变量，变量取值为字符串
str_col1=['MORTGAGE', 'NONE', 'OTHER', 'OWN', 'RENT',
          'NONE', 'NONE', 'OTHER', 'OTHER', 'RENT']
str_col2=['Not Verified', 'Source Verified', 'Verified','Not Verified', 
          'Source Verified', 'Not Verified', 'Source Verified', 'Verified',
          'Source Verified', 'Verified']
df_str=pd.DataFrame({'str_col1':str_col1,'str_col2':str_col2})

#DictVectorizer编码
v=DictVectorizer(sparse=False)
v.fit(df_str.to_dict('records'))
print(df_str.to_dict('records'))
x1=v.transform(df_str.to_dict('records'))
print(x1)

#编码规则见过的数据
print(v.transform({'str_col1':'MORTGAGE','str_col2':'Source Verified'}))

#编码规则未见过的数据：全0
print(v.transform({'col1':'unknown1','col2':'unknow2'}))


[{'str_col1': 'MORTGAGE', 'str_col2': 'Not Verified'}, {'str_col1': 'NONE', 'str_col2': 'Source Verified'}, {'str_col1': 'OTHER', 'str_col2': 'Verified'}, {'str_col1': 'OWN', 'str_col2': 'Not Verified'}, {'str_col1': 'RENT', 'str_col2': 'Source Verified'}, {'str_col1': 'NONE', 'str_col2': 'Not Verified'}, {'str_col1': 'NONE', 'str_col2': 'Source Verified'}, {'str_col1': 'OTHER', 'str_col2': 'Verified'}, {'str_col1': 'OTHER', 'str_col2': 'Source Verified'}, {'str_col1': 'RENT', 'str_col2': 'Verified'}]
[[1. 0. 0. 0. 0. 1. 0. 0.]
 [0. 1. 0. 0. 0. 0. 1. 0.]
 [0. 0. 1. 0. 0. 0. 0. 1.]
 [0. 0. 0. 1. 0. 1. 0. 0.]
 [0. 0. 0. 0. 1. 0. 1. 0.]
 [0. 1. 0. 0. 0. 1. 0. 0.]
 [0. 1. 0. 0. 0. 0. 1. 0.]
 [0. 0. 1. 0. 0. 0. 0. 1.]
 [0. 0. 1. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1. 0. 0. 1.]]
[[1. 0. 0. 0. 0. 0. 1. 0.]]
[[0. 0. 0. 0. 0. 0. 0. 0.]]


In [2]:
df_str

str_col1         str_col2
0  MORTGAGE     Not Verified
1      NONE  Source Verified
2     OTHER         Verified
3       OWN     Not Verified
4      RENT  Source Verified
5      NONE     Not Verified
6      NONE  Source Verified
7     OTHER         Verified
8     OTHER  Source Verified
9      RENT         Verified

In [71]:
#LabelEncoder不支持同时对多列进行自然编码，需要每列单独自然编码后再合并列
#导入工具包
import pandas as pd
import numpy as np
from sklearn.preprocessing import OneHotEncoder,LabelEncoder
from sklearn.feature_extraction import DictVectorizer

#创建示例数据：离散无序变量，变量取值为字符串
str_col1=['MORTGAGE', 'NONE', 'OTHER', 'OWN', 'RENT',
          'NONE', 'NONE', 'OTHER', 'OTHER', 'RENT']
str_col2=['Not Verified', 'Source Verified', 'Verified','Not Verified', 
          'Source Verified', 'Not Verified', 'Source Verified', 'Verified',
          'Source Verified', 'Verified']
df_str=pd.DataFrame({'str_col1':str_col1,'str_col2':str_col2})

#对列df_str['str_col1']自然编码
le_col1=LabelEncoder()
col1=le_col1.fit_transform(df_str['str_col1'])

#对列df_str['str_col2']自然编码
le_col2=LabelEncoder()
col2=le_col2.fit_transform(df_str['str_col2'])

#合并自然编码值为array(为便于之后OneHotEncoder编码，将arr_str的shape做到与df_str一致)
arr_num=np.vstack([col1,col2]).T
print('{:*^60}'.format('原数据'))
print(df_str)
print('{:*^60}'.format('LabelEncoder之后的数据'))
print(arr_num)

#DictVectorizer对整数表示的离散无需变量值编码
v=DictVectorizer(sparse=False)
v.fit(pd.DataFrame(arr_num).to_dict('records'))
x3=v.transform(pd.DataFrame(arr_num).to_dict('records'))
print('{:*^60}'.format('DictVectorizer对整数编译之后的结果'))
print(x3)

#DictVectorizer对字符串编码
v=DictVectorizer(sparse=False)
v.fit(df_str.to_dict('records'))
x1=v.transform(df_str.to_dict('records'))
print('{:*^60}'.format('DictVectorizer对字符串编译之后的结果'))
print(x1)

#OneHotEncoder对整数表示的离散无需变量值编码
ohe_num=OneHotEncoder(sparse=False,handle_unknown='ignore')
x2=ohe_num.fit_transform(arr_num)
print('{:*^60}'.format('OneHotEncoder对整数编译之后的结果'))
print(x2)


#OneHotEncoder对字符串表示的离散无需变量值编码
ohe_num1=OneHotEncoder(sparse=False,handle_unknown='ignore')
x4=ohe_num1.fit_transform(df_str)
print('{:*^60}'.format('OneHotEncoder对字符串编译之后的结果'))
print(x4)


#对比使用DictVectorizer编码结果：两者相等；
print('{:*^60}'.format('对比使用DictVectorizer字符串编码结果：两者相等'))
print((x1==x2).reshape(-1,).min()) #结果为True表相等，False表示存在不相等的编码值

#OneHotEncoder对编码规则见过的数据编码
print('{:*^60}'.format('OneHotEncoder对编码规则见过的数据编码'))
print(ohe_num.transform([[1,2]]))

#OneHotEncoder对编码规则见过的数据编码：handle_unknown='ignore'时，全0；默认'error'，遇到编码规则未见过数据时报错
print('{:*^60}'.format('OneHotEncoder对未见过的数据编码'))
print(ohe_num.transform([[6,8]]))


****************************原数据*****************************
   str_col1         str_col2
0  MORTGAGE     Not Verified
1      NONE  Source Verified
2     OTHER         Verified
3       OWN     Not Verified
4      RENT  Source Verified
5      NONE     Not Verified
6      NONE  Source Verified
7     OTHER         Verified
8     OTHER  Source Verified
9      RENT         Verified
*********************LabelEncoder之后的数据**********************
[[0 0]
 [1 1]
 [2 2]
 [3 0]
 [4 1]
 [1 0]
 [1 1]
 [2 2]
 [2 1]
 [4 2]]
******************DictVectorizer对整数编译之后的结果******************
[[0. 0.]
 [1. 1.]
 [2. 2.]
 [3. 0.]
 [4. 1.]
 [1. 0.]
 [1. 1.]
 [2. 2.]
 [2. 1.]
 [4. 2.]]
*****************DictVectorizer对字符串编译之后的结果******************
[[1. 0. 0. 0. 0. 1. 0. 0.]
 [0. 1. 0. 0. 0. 0. 1. 0.]
 [0. 0. 1. 0. 0. 0. 0. 1.]
 [0. 0. 0. 1. 0. 1. 0. 0.]
 [0. 0. 0. 0. 1. 0. 1. 0.]
 [0. 1. 0. 0. 0. 1. 0. 0.]
 [0. 1. 0. 0. 0. 0. 1. 0.]
 [0. 0. 1. 0. 0. 0. 0. 1.]
 [0. 0. 1. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1. 0. 0. 1.]]
****

In [75]:
#创建示例数据：离散无序变量，变量取值为整数
#仅看数字它有顺序，但这里我们只想要这些数字标记取值的作用
num_col1=[1, 2, 3, 4, 5,2, 2, 3, 3, 5]
num_col2=[1, 2, 3,1, 2,1, 2, 1,2, 3]
df_num=pd.DataFrame({'num_col1':num_col1,'num_col2':num_col2})

#DictVectorizer对数值型变量值编码，结果仍是原值，未起到编码目的
v_num2=DictVectorizer(sparse=False)
print(v_num2.fit_transform(df_num.to_dict('records')))

#OneHotEncoder编码
ohe_num=OneHotEncoder(sparse=False)
print(ohe_num.fit_transform(df_num))

#OneHotEncoder编码
ohe_num=OneHotEncoder(sparse=True)
print(ohe_num.fit_transform(df_num))


[[1. 1.]
 [2. 2.]
 [3. 3.]
 [4. 1.]
 [5. 2.]
 [2. 1.]
 [2. 2.]
 [3. 1.]
 [3. 2.]
 [5. 3.]]
[[1. 0. 0. 0. 0. 1. 0. 0.]
 [0. 1. 0. 0. 0. 0. 1. 0.]
 [0. 0. 1. 0. 0. 0. 0. 1.]
 [0. 0. 0. 1. 0. 1. 0. 0.]
 [0. 0. 0. 0. 1. 0. 1. 0.]
 [0. 1. 0. 0. 0. 1. 0. 0.]
 [0. 1. 0. 0. 0. 0. 1. 0.]
 [0. 0. 1. 0. 0. 1. 0. 0.]
 [0. 0. 1. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1. 0. 0. 1.]]
  (0, 0)	1.0
  (0, 5)	1.0
  (1, 1)	1.0
  (1, 6)	1.0
  (2, 2)	1.0
  (2, 7)	1.0
  (3, 3)	1.0
  (3, 5)	1.0
  (4, 4)	1.0
  (4, 6)	1.0
  (5, 1)	1.0
  (5, 5)	1.0
  (6, 1)	1.0
  (6, 6)	1.0
  (7, 2)	1.0
  (7, 5)	1.0
  (8, 2)	1.0
  (8, 6)	1.0
  (9, 4)	1.0
  (9, 7)	1.0


In [76]:
ohe_num.get_feature_names()

array(['x0_1', 'x0_2', 'x0_3', 'x0_4', 'x0_5', 'x1_1', 'x1_2', 'x1_3'],
      dtype=object)

# 结论：
在数据预处理中，对离散无序数据的编码通常的做法是：在训练集上生成编码规则，测试集的数据编码直接调用已生成的规则，以确保模型可以处理所有数据。
当测试集出现基于训练集的编码规则没见过的数据时，DictVectorizer、OneHotEncoder将未见过数据编码全为0来处理；但是但get_dummies没有这样的用法，它只能在新数据上新建一套编码规则，当训练集上的编码规则与测试集上的不完全一致时，get_dummies也没有相应的应对措施，这时模型就不知道该如何处理未见过的数据了。

**综上：

1、字符串表示离散无序变量取值时，独热编码使用DictVectorizer，若使用LabelEncoder + OneHotEncoder，麻烦；

2、整数表示离散无序变量取值时，独热编码使用OneHotEncoder；
**
————————————————
版权声明：本文为CSDN博主「Custom996」的原创文章，遵循CC 4.0 BY-SA版权协议，转载请附上原文出处链接及本声明。
原文链接：https://blog.csdn.net/qq_40913605/article/details/86688227
